@id=f4c264ed-c505-4bec-a0b1-1fdd9c03fd55

PUT http://localhost:5244/breakfasts/{{id}}
Content-Type: application/json

{
  "name": "Vegan Sunshine 2",
  "description": "Vegan everything! Join us for a healthy breakfast..",
  "startDateTime": "2022-04-08T08:00:00",
  "endDateTime": "2022-04-08T11:00:00",
  "savory": ["Oatmeal", "Avocado Toast", "Omelette", "Salad"],
  "Sweet": ["Cookie"]
}